import org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

plugins {
    java
    eclipse
    idea
    war
    id("org.akhikhl.gretty") version "2.0.0"
}

version = "1.1"

defaultTasks("clean","build")

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.slf4j:slf4j-api:1.7.25")
    implementation(group="ch.qos.logback",name="logback-classic",version="1.2.3")
    providedCompile(group="javax.servlet",name="javax.servlet-api",version="3.1.0")
    testImplementation(group = "org.testng", name = "testng", version = "6.9.13.6")
}

gretty{
    // supported values:
    // 'jetty7', 'jetty8', 'jetty9', 'jetty93', 'jetty94', 'tomcat7', 'tomcat8'
    servletContainer = "jetty9"
    httpPort=8080
    contextPath = "/gradle-war"
}

tasks.war {
    archiveFileName.set("gradle-war.war")
}

val test = tasks.test{
    testLogging{
        // show standard out and standard error of the test JVM(s) on the console
        showStandardStreams=true
        exceptionFormat= FULL
    }
    useTestNG{
        excludeGroups("integration")
    }
}

val integrationTest  by tasks.registering(Test::class){
    dependsOn(test)
    testLogging{
        // show standard out and standard error of the test JVM(s) on the console
        showStandardStreams=true
        exceptionFormat= FULL
    }
    useTestNG{
        includeGroups("integration")
    }
}
