/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'robertkuhar' at '8/14/16 5:37 PM' with Gradle 2.14.1
 *
 * @author robertkuhar, @date 8/14/16 5:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
